### ISSUE TITLE
Exception: ERROR: This is not rar file.

### ISSUE THREAD

**Issue by Sopor** [opensubtitlesdev/service.subtitles.opensubtitles-com#4]
I get this error message when i try to search for subtitles:

```
2023-01-26 23:45:34.280 T:8588    error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://service.subtitles.opensubtitles-com/?action=search&languages=English%2cSwedish&preferredlanguage=Swedish
2023-01-26 23:45:37.806 T:11404   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'Exception'>
                                                   Error Contents: ERROR: This is not rar file.
                                                   Traceback (most recent call last):
                                                     File "E:\Utils\Media\Kodi 20\portable_data\addons\service.subtitles.opensubtitles-com\service.py", line 8, in <module>
                                                       SubtitleDownloader().handle_action()
                                                     File "E:\Utils\Media\Kodi 20\portable_data\addons\service.subtitles.opensubtitles-com\resources\lib\subtitle_downloader.py", line 58, in handle_action
                                                       self.search()
                                                     File "E:\Utils\Media\Kodi 20\portable_data\addons\service.subtitles.opensubtitles-com\resources\lib\subtitle_downloader.py", line 63, in search
                                                       file_data = get_file_data(get_file_path())
                                                     File "E:\Utils\Media\Kodi 20\portable_data\addons\service.subtitles.opensubtitles-com\resources\lib\file_operations.py", line 27, in get_file_data
                                                       item["file_size"], item["moviehash"] = hash_file(item["file_original_path"], item["rar"])
                                                     File "E:\Utils\Media\Kodi 20\portable_data\addons\service.subtitles.opensubtitles-com\resources\lib\file_operations.py", line 35, in hash_file
                                                       return hash_rar(file_path)
                                                     File "E:\Utils\Media\Kodi 20\portable_data\addons\service.subtitles.opensubtitles-com\resources\lib\file_operations.py", line 67, in hash_rar
                                                       raise Exception("ERROR: This is not rar file.")
                                                   Exception: ERROR: This is not rar file.
                                                   -->End of Python script error report<--
```

I'm playing directly from a RAR archive, so the addon will search for the subtitles using the file name.

Kodi 20 on Windows 10

**Comment by roxsman** [comment]
Getting the exact same error in kodi log when searching for subs using opensubtitles.com addon. Kodi 20.1 on Libreelec 11.0.1

**Comment by roxsman** [comment]
Not judging, just curious; is this repo being maintained?

**Comment by opensubtitlesdev** [comment]
Well we do the best we can, but totally overflown with work, looking for a reliable python developper who can understand kodi for several years now, a few applied, they all gave up.
